import { RemoteJobHunterSceneConfig } from '@features/remote-job-hunter/phaser/models/office-zone.model';

export const REMOTE_JOB_HUNTER_SCENE_COLORS = {
  cyan: {
    text: '#22d3ee',
    hex: 0x22d3ee,
  },
  white: {
    text: '#ffffff',
  },
  slate: {
    dark: 0x0f172a,
  },
  angular: 0xdd0031,
  typescript: 0x3178c6,
  rxjs: 0xb7178c,
  english: 0x16a34a,
  coffee: 0x7c4a2d,
  amber: 0xf59e0b,
  red: 0xf87171,
} as const;

export const REMOTE_JOB_HUNTER_SCENE: RemoteJobHunterSceneConfig = {
  size: {
    width: 1000,
    height: 500,
  },
  layout: {
    padding: 16,
    headerHeight: 44,
  },
  colors: {
    title: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.text,
    text: REMOTE_JOB_HUNTER_SCENE_COLORS.white.text,
    player: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,

    interactionKeyText: '#0f172a',
    interactionKeyFill: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,
    interactionKeyBorder: 0xffffff,

    interactionPanelBackground: REMOTE_JOB_HUNTER_SCENE_COLORS.slate.dark,
    interactionPanelBorder: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,
  },
  title: {
    text: 'Remote Job Hunter',
    fontSize: '28px',
  },
  player: {
    label: 'Junior',
    size: 20,
    speed: 3,
    labelGap: 10,
    labelOffsetX: 12,
    startPosition: {
      x: 500,
      y: 250,
    },
    labelFontSize: '14px',
  },
  zones: {
    width: 120,
    height: 64,
    opacity: 0.9,
    labelFontSize: '13px',
    collisionPadding: 8,
    interactionPadding: 46,
    interactionHintGap: 12,
    items: [
      {
        id: 'angular-desk',
        label: 'Angular Desk',
        actionLabel: 'Study Angular',
        feedbackLabel: '+5 Angular',
        feedbackColor: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,
        actionType: 'study-angular',
        x: 140,
        y: 160,
        color: REMOTE_JOB_HUNTER_SCENE_COLORS.angular,
      },
      {
        id: 'ts-shelf',
        label: 'TS Shelf',
        actionLabel: 'Practice TypeScript',
        feedbackLabel: '+5 TypeScript',
        feedbackColor: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,
        actionType: 'practice-typescript',
        x: 820,
        y: 190,
        color: REMOTE_JOB_HUNTER_SCENE_COLORS.typescript,
      },
      {
        id: 'rxjs-shelf',
        label: 'RxJS Shelf',
        actionLabel: 'Practice RxJS',
        feedbackLabel: '+4 RxJS',
        feedbackColor: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,
        actionType: 'practice-rxjs',
        x: 140,
        y: 340,
        color: REMOTE_JOB_HUNTER_SCENE_COLORS.rxjs,
      },
      {
        id: 'english-book',
        label: 'English Book',
        actionLabel: 'Practice English',
        feedbackLabel: '+3 English',
        feedbackColor: REMOTE_JOB_HUNTER_SCENE_COLORS.cyan.hex,
        actionType: 'practice-english',
        x: 820,
        y: 370,
        color: REMOTE_JOB_HUNTER_SCENE_COLORS.english,
      },
      {
        id: 'coffee-break',
        label: 'Coffee Break',
        actionLabel: 'Restore Energy',
        feedbackLabel: '+Energy',
        feedbackColor: REMOTE_JOB_HUNTER_SCENE_COLORS.amber,
        actionType: 'coffee-break',
        x: 500,
        y: 440,
        color: REMOTE_JOB_HUNTER_SCENE_COLORS.coffee,
      },
    ],
  },
  interaction: {
    keyText: 'E',
    panelTitle: 'Interaction',
    hintFontSize: '14px',
    keyBoxSize: 24,
    feedbackFontSize: '14px',
    feedbackDuration: 900,
    cooldownMs: 700,
    panel: {
      x: 675,
      y: 30,
      width: 520,
      height: 34,
    },
  },
};
