import { InterviewQuestion } from '@features/remote-job-hunter/models/interview-question.model';

export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'junior-angular-template-binding',
    interviewLevel: 1,
    questionEn: 'What is Angular template binding used for?',
    questionRu: 'Для чего используется привязка данных в шаблоне Angular?',
    answersEn: [
      'To connect component data with the template',
      'To create database tables',
      'To configure Docker',
      'To compile SCSS files',
    ],
    answersRu: [
      'Чтобы связать данные компонента с шаблоном',
      'Чтобы создавать таблицы базы данных',
      'Чтобы настраивать Docker',
      'Чтобы компилировать SCSS-файлы',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'junior-typescript-interface',
    interviewLevel: 1,
    questionEn: 'What is the main purpose of a TypeScript interface?',
    questionRu: 'Для чего в первую очередь используется TypeScript interface?',
    answersEn: [
      'To define the shape of an object',
      'To run code in the browser',
      'To create CSS animations',
      'To start an HTTP server',
    ],
    answersRu: [
      'Для описания структуры объекта',
      'Для выполнения кода в браузере',
      'Для создания CSS-анимаций',
      'Для запуска HTTP-сервера',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'junior-rxjs-observable',
    interviewLevel: 1,
    questionEn: 'What is an Observable in RxJS?',
    questionRu: 'Что такое Observable в RxJS?',
    answersEn: [
      'A stream of values over time',
      'A CSS selector',
      'A database transaction',
      'A TypeScript decorator only for services',
    ],
    answersRu: [
      'Поток значений во времени',
      'CSS-селектор',
      'Транзакция базы данных',
      'TypeScript-декоратор только для сервисов',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'middle-rxjs-switchmap',
    interviewLevel: 2,
    questionEn: 'Which RxJS operator cancels the previous inner observable?',
    questionRu: 'Какой оператор RxJS отменяет предыдущий внутренний Observable?',
    answersEn: ['mergeMap', 'concatMap', 'switchMap', 'forkJoin'],
    answersRu: ['mergeMap', 'concatMap', 'switchMap', 'forkJoin'],
    correctAnswerIndex: 2,
  },
  {
    id: 'middle-angular-signals-computed',
    interviewLevel: 2,
    questionEn: 'What is Angular computed() used for?',
    questionRu: 'Для чего используется Angular computed()?',
    answersEn: [
      'To create derived reactive values',
      'To send HTTP requests',
      'To register routes',
      'To create CSS animations',
    ],
    answersRu: [
      'Для создания вычисляемых реактивных значений',
      'Для отправки HTTP-запросов',
      'Для регистрации маршрутов',
      'Для создания CSS-анимаций',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'middle-onpush',
    interviewLevel: 2,
    questionEn: 'What is the main idea of ChangeDetectionStrategy.OnPush?',
    questionRu: 'В чём основная идея ChangeDetectionStrategy.OnPush?',
    answersEn: [
      'Angular checks the component only on specific triggers',
      'Angular disables all events',
      'Angular removes lifecycle hooks',
      'Angular automatically creates services',
    ],
    answersRu: [
      'Angular проверяет компонент только при определённых триггерах',
      'Angular отключает все события',
      'Angular удаляет lifecycle hooks',
      'Angular автоматически создаёт сервисы',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'senior-di-hierarchy',
    interviewLevel: 3,
    questionEn: 'Why is Angular dependency injection hierarchical?',
    questionRu: 'Почему dependency injection в Angular является иерархическим?',
    answersEn: [
      'Different parts of the app can have different provider scopes',
      'It makes CSS inheritance faster',
      'It replaces routing',
      'It prevents TypeScript compilation errors',
    ],
    answersRu: [
      'Разные части приложения могут иметь разные области видимости провайдеров',
      'Это ускоряет наследование CSS',
      'Это заменяет routing',
      'Это предотвращает ошибки компиляции TypeScript',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'senior-rxjs-concatmap',
    interviewLevel: 3,
    questionEn: 'When is concatMap usually preferred?',
    questionRu: 'Когда обычно предпочтительнее использовать concatMap?',
    answersEn: [
      'When inner operations must run sequentially in order',
      'When previous requests must always be cancelled',
      'When all requests must run in parallel',
      'When no subscription is needed',
    ],
    answersRu: [
      'Когда внутренние операции должны выполняться последовательно и по порядку',
      'Когда предыдущие запросы всегда нужно отменять',
      'Когда все запросы должны выполняться параллельно',
      'Когда подписка не нужна',
    ],
    correctAnswerIndex: 0,
  },
  {
    id: 'senior-trackby',
    interviewLevel: 3,
    questionEn: 'Why is trackBy or track expression important for large lists?',
    questionRu: 'Почему trackBy или track expression важны для больших списков?',
    answersEn: [
      'It helps Angular reuse DOM nodes and avoid unnecessary re-rendering',
      'It converts arrays into Observables',
      'It disables change detection',
      'It automatically sorts the list',
    ],
    answersRu: [
      'Помогает Angular переиспользовать DOM-элементы и избегать лишней перерисовки',
      'Преобразует массивы в Observables',
      'Отключает change detection',
      'Автоматически сортирует список',
    ],
    correctAnswerIndex: 0,
  },
];
